/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormSecurityAnalisis.java
 *
 * Created on Apr 24, 2015, 2:16:17 PM
 */
package ui;

import entity.BitmapImage;
import imagesecurityadvancedhillcipher.ImageReader;
import imagesecurityadvancedhillcipher.ImageViewer;
import imagesecurityadvancedhillcipher.SecurityAnalysis;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import utility.Util;
import org.jfree.chart.ChartFactory; //Jfreechart 
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import utility.ExtensionFileFilter;
 

/**
 *
 * @author Fiqih Amrullah
 */
public class FormSecurityAnalisis extends javax.swing.JFrame {
   BitmapImage gbrPlain;
   BitmapImage gbrCipher;
    /** Creates new form FormSecurityAnalisis */
    public FormSecurityAnalisis() 
    {
        initComponents();
        Util.TengahWindow(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        panelYellow1 = new ui.PanelYellow();
        btnBrowsePlainImage = new ui.ButtonGlass();
        btnBrowseCipherImage = new ui.ButtonGlass();
        jlblGbrPlain = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlblGbrCipher = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelYellow2 = new ui.PanelYellow();
        btnRunAnalysis = new ui.ButtonGlass();
        btnTutup = new ui.ButtonGlass();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jlblEntropy = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jlblPlainHoriz = new javax.swing.JLabel();
        jlblPlainVer = new javax.swing.JLabel();
        jlblPlainDiag = new javax.swing.JLabel();
        jlblCipherHoriz = new javax.swing.JLabel();
        jlblCipherVer = new javax.swing.JLabel();
        jlblCipherDiag = new javax.swing.JLabel();
        jlblCipherHoriz1 = new javax.swing.JLabel();
        jlblCipherHoriz2 = new javax.swing.JLabel();
        jlblCipherHoriz3 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Analysis");

        panelYellow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBrowsePlainImage.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowsePlainImage.setText("Browse..");
        btnBrowsePlainImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsePlainImageActionPerformed(evt);
            }
        });
        panelYellow1.add(btnBrowsePlainImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 130, 30));

        btnBrowseCipherImage.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowseCipherImage.setText("Browse..");
        btnBrowseCipherImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseCipherImageActionPerformed(evt);
            }
        });
        panelYellow1.add(btnBrowseCipherImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 130, 30));

        jlblGbrPlain.setForeground(new java.awt.Color(255, 255, 255));
        jlblGbrPlain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblGbrPlain.setText("- Browse Image -");
        jlblGbrPlain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelYellow1.add(jlblGbrPlain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 202, 240));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelYellow1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 64, 18, 330));

        jlblGbrCipher.setForeground(new java.awt.Color(255, 255, 255));
        jlblGbrCipher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblGbrCipher.setText("- Browse Image -");
        jlblGbrCipher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelYellow1.add(jlblGbrCipher, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 210, 240));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PLAIN");
        panelYellow1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CIPHER");
        panelYellow1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 90, 30));

        btnRunAnalysis.setForeground(new java.awt.Color(255, 255, 255));
        btnRunAnalysis.setText("Run Analysis");
        btnRunAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunAnalysisActionPerformed(evt);
            }
        });

        btnTutup.setForeground(new java.awt.Color(255, 255, 255));
        btnTutup.setText("Close");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Information Entropy");

        jlblEntropy.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblEntropy.setForeground(new java.awt.Color(255, 255, 0));
        jlblEntropy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblEntropy.setText("0");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Correlation Coeficient");

        jlblPlainHoriz.setForeground(new java.awt.Color(255, 255, 255));
        jlblPlainHoriz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPlainHoriz.setText("0");

        jlblPlainVer.setForeground(new java.awt.Color(255, 255, 255));
        jlblPlainVer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPlainVer.setText("0");

        jlblPlainDiag.setForeground(new java.awt.Color(255, 255, 255));
        jlblPlainDiag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPlainDiag.setText("0");

        jlblCipherHoriz.setForeground(new java.awt.Color(255, 255, 255));
        jlblCipherHoriz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCipherHoriz.setText("0");

        jlblCipherVer.setForeground(new java.awt.Color(255, 255, 255));
        jlblCipherVer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCipherVer.setText("0");

        jlblCipherDiag.setForeground(new java.awt.Color(255, 255, 255));
        jlblCipherDiag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCipherDiag.setText("0");

        jlblCipherHoriz1.setForeground(new java.awt.Color(255, 255, 255));
        jlblCipherHoriz1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCipherHoriz1.setText("V");

        jlblCipherHoriz2.setForeground(new java.awt.Color(255, 255, 255));
        jlblCipherHoriz2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCipherHoriz2.setText("H");

        jlblCipherHoriz3.setForeground(new java.awt.Color(255, 255, 255));
        jlblCipherHoriz3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCipherHoriz3.setText("D");

        javax.swing.GroupLayout panelYellow2Layout = new javax.swing.GroupLayout(panelYellow2);
        panelYellow2.setLayout(panelYellow2Layout);
        panelYellow2Layout.setHorizontalGroup(
            panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addGroup(panelYellow2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTutup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRunAnalysis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelYellow2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelYellow2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblPlainDiag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblPlainVer, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jlblPlainHoriz, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCipherHoriz1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCipherHoriz2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCipherHoriz3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCipherVer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCipherHoriz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCipherDiag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(panelYellow2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jlblEntropy, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelYellow2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelYellow2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelYellow2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        panelYellow2Layout.setVerticalGroup(
            panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelYellow2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnRunAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jlblEntropy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelYellow2Layout.createSequentialGroup()
                        .addGroup(panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblPlainHoriz, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCipherHoriz2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblPlainVer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblPlainDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelYellow2Layout.createSequentialGroup()
                        .addComponent(jlblCipherHoriz, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCipherVer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCipherHoriz1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelYellow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCipherDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCipherHoriz3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelYellow1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelYellow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelYellow1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(panelYellow2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void ShowHistogram(int[][] pixel, String status, String Name) 
     {

        int[][] count = new int[1][256];        

        int Gray = 0;

        for (int i = 0; i < pixel.length; i++) {
            for (int j = 0; j < pixel[i].length; j++) {                
               
                int gray = pixel[i][j]; 
                count[Gray][gray]++;
                
            }
        }

        //untuk tampil ke jfreechart
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int f = 0; f < 256; f++) {

            dataset.addValue(count[0][f], "Gray", new Integer(f));
          
        }

        JFreeChart chart = ChartFactory.createAreaChart("Histogram Grayscale ( "+Name+" )", "Nilai","Frekuensi",dataset,PlotOrientation.VERTICAL, true, true, false);

        ChartFrame frame=new ChartFrame("Histogram",chart);
        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        plot.setBackgroundPaint(Color.WHITE);
        plot.setRangeGridlinePaint(Color.white);
        plot.getRenderer().setSeriesPaint(0, Color.gray);

        frame.setSize(500,350);
        frame.setVisible(true);
        frame.setLocation(380, 200);
    }
    
private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_btnTutupActionPerformed

private void btnBrowsePlainImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowsePlainImageActionPerformed
// TODO add your handling code here:
    // TODO add your handling code here:
    JFileChooser flchooser = new JFileChooser();
      FileFilter filter1 = new ExtensionFileFilter("Picture Files", new String[] { "JPG","TIFF","PNG","BMP"});
    flchooser.setFileFilter(filter1);
    int tanggapan = flchooser.showOpenDialog(this);   
    if(tanggapan==JFileChooser.APPROVE_OPTION)
    {
        BufferedImage img=null;
        try
        {
         img = ImageIO.read(flchooser.getSelectedFile());
        }catch(IOException ex)
        {
            
        }
       
        ImageIcon imgicon = new ImageIcon(img); 
        ImageReader imgLoader = new ImageReader();
        imgLoader.readPixelsFrom(imgicon);
        gbrPlain = imgLoader.getImage();       
        ImageViewer imgv = new ImageViewer();
        imgv.setImage(gbrPlain);
        imgv.setViewer(jlblGbrPlain);
        imgv.viewImageDefault();
           
    }
}//GEN-LAST:event_btnBrowsePlainImageActionPerformed

private void btnBrowseCipherImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseCipherImageActionPerformed
// TODO add your handling code here:
    JFileChooser flchooser = new JFileChooser();
      FileFilter filter1 = new ExtensionFileFilter("Picture Files", new String[] { "JPG","TIFF","PNG","BMP"});
    flchooser.setFileFilter(filter1);
    int tanggapan = flchooser.showOpenDialog(this);   
    if(tanggapan==JFileChooser.APPROVE_OPTION)
    {
        BufferedImage img=null;
        try
        {
         img = ImageIO.read(flchooser.getSelectedFile());
        }catch(IOException ex)
        {
            
        }
       
        ImageIcon imgicon = new ImageIcon(img); 
        ImageReader imgLoader = new ImageReader();
        imgLoader.readPixelsFrom(imgicon);
        gbrCipher = imgLoader.getImage();       
        ImageViewer imgv = new ImageViewer();
        imgv.setImage(gbrCipher);
        imgv.setViewer(jlblGbrCipher);
        imgv.viewImageDefault();
           
    }
}//GEN-LAST:event_btnBrowseCipherImageActionPerformed

private void btnRunAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunAnalysisActionPerformed
// TODO add your handling code here:
    SecurityAnalysis sa = new SecurityAnalysis(gbrPlain, gbrCipher);
    
    int hist[][] = gbrPlain.getPixelAsli();
    ShowHistogram(hist,"Plain","Image 1");
    
    int hist2[][] = gbrCipher.getPixelAsli();
    ShowHistogram(hist2,"Cipher","Image 2");
    
    jlblEntropy.setText(String.valueOf(sa.InformationEntropy()));
  
    
    int plain[][] = gbrPlain.getPixelAsli();
    jlblPlainHoriz.setText("" + sa.CorrelationCoef(plain,255,"horizontal"));
    jlblPlainVer.setText("" + sa.CorrelationCoef(plain,255,"vertical"));
    jlblPlainDiag.setText("" + sa.CorrelationCoef(plain,255,"diagonal"));
     
        
    //for image 2
    int cipher[][] = gbrCipher.getPixelAsli();
    jlblCipherHoriz.setText("" + sa.CorrelationCoef(cipher,255,"horizontal"));
    jlblCipherVer.setText("" + sa.CorrelationCoef(cipher,255,"vertical"));
    jlblCipherDiag.setText("" + sa.CorrelationCoef(cipher,255,"diagonal"));
      
    
}//GEN-LAST:event_btnRunAnalysisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSecurityAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSecurityAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSecurityAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSecurityAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormSecurityAnalisis().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.ButtonGlass btnBrowseCipherImage;
    private ui.ButtonGlass btnBrowsePlainImage;
    private ui.ButtonGlass btnRunAnalysis;
    private ui.ButtonGlass btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlblCipherDiag;
    private javax.swing.JLabel jlblCipherHoriz;
    private javax.swing.JLabel jlblCipherHoriz1;
    private javax.swing.JLabel jlblCipherHoriz2;
    private javax.swing.JLabel jlblCipherHoriz3;
    private javax.swing.JLabel jlblCipherVer;
    private javax.swing.JLabel jlblEntropy;
    private javax.swing.JLabel jlblGbrCipher;
    private javax.swing.JLabel jlblGbrPlain;
    private javax.swing.JLabel jlblPlainDiag;
    private javax.swing.JLabel jlblPlainHoriz;
    private javax.swing.JLabel jlblPlainVer;
    private ui.PanelYellow panelYellow1;
    private ui.PanelYellow panelYellow2;
    // End of variables declaration//GEN-END:variables
}
