/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 
package ui;

import utility.Util;

/**
 *
 * @author Fiqih Amrullah
 */
public class FormMain extends javax.swing.JFrame {

    /** Creates new form FormMain */
    public FormMain() {
        initComponents();
        Util.TengahWindow(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelYellow1 = new ui.PanelYellow();
        btnEnkripsiGambar = new ui.ButtonGlass();
        btnDekripsiGambar = new ui.ButtonGlass();
        btnShowSecurityAnalisis = new ui.ButtonGlass();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Utama");
        setResizable(false);

        btnEnkripsiGambar.setText("Enkripsi Gambar");
        btnEnkripsiGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnkripsiGambarActionPerformed(evt);
            }
        });

        btnDekripsiGambar.setText("Dekripsi Gambar");
        btnDekripsiGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDekripsiGambarActionPerformed(evt);
            }
        });

        btnShowSecurityAnalisis.setText("Analisa Keamanan");
        btnShowSecurityAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSecurityAnalisisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelYellow1Layout = new javax.swing.GroupLayout(panelYellow1);
        panelYellow1.setLayout(panelYellow1Layout);
        panelYellow1Layout.setHorizontalGroup(
            panelYellow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnEnkripsiGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnDekripsiGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnShowSecurityAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        panelYellow1Layout.setVerticalGroup(
            panelYellow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(panelYellow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelYellow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDekripsiGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addComponent(btnShowSecurityAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addComponent(btnEnkripsiGambar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addGap(149, 149, 149))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelYellow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(panelYellow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnShowSecurityAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSecurityAnalisisActionPerformed
// TODO add your handling code here:
    //this.dispose();
    FormSecurityAnalisis frmfsa = new FormSecurityAnalisis();
    frmfsa.setVisible(true);
}//GEN-LAST:event_btnShowSecurityAnalisisActionPerformed

private void btnEnkripsiGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnkripsiGambarActionPerformed
// TODO add your handling code here:
    FormEncryptImage frmEncImae = new FormEncryptImage();
    frmEncImae.setVisible(true);
    
    
}//GEN-LAST:event_btnEnkripsiGambarActionPerformed

private void btnDekripsiGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDekripsiGambarActionPerformed
// TODO add your handling code here:
    FormDecryptImage frmDecryptImage = new FormDecryptImage();
    frmDecryptImage.setVisible(true);
}//GEN-LAST:event_btnDekripsiGambarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.ButtonGlass btnDekripsiGambar;
    private ui.ButtonGlass btnEnkripsiGambar;
    private ui.ButtonGlass btnShowSecurityAnalisis;
    private ui.PanelYellow panelYellow1;
    // End of variables declaration//GEN-END:variables
}
