/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormDecryptImage.java
 *
 * Created on Apr 24, 2015, 1:29:41 PM
 */
package ui;


import advancedhillcipher.HillCipher;
import advancedhillcipher.Matrix;
import advancedhillcipher.Permutation;
import entity.BitmapImage;
import imagesecurityadvancedhillcipher.Affine;
import imagesecurityadvancedhillcipher.ImageReader;
import imagesecurityadvancedhillcipher.ImageViewer;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import utility.ExtensionFileFilter;
import utility.Util;

/**
 *
 * @author Fiqih Amrullah
 */
public class FormDecryptImage extends javax.swing.JFrame {
 BitmapImage gbr1;
   BitmapImage gbr2;
    /** Creates new form FormDecryptImage */
    public FormDecryptImage() 
    {
        initComponents();
        Util.TengahWindow(this);
        gbr1=null;
        gbr2=null;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelYellow1 = new ui.PanelYellow();
        jlblGambarUji1 = new javax.swing.JLabel();
        jlblGambarUji2 = new javax.swing.JLabel();
        panelYellow2 = new ui.PanelYellow();
        jPanel1 = new javax.swing.JPanel();
        jtxtk2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtk1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnJalankanDekripsi = new ui.ButtonGlass();
        btnSimpanGambar = new ui.ButtonGlass();
        btnKeluar = new ui.ButtonGlass();
        jLabel1 = new javax.swing.JLabel();
        jrbtnMetodeAT = new javax.swing.JRadioButton();
        jrbtnMetodeATAHC = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxtSeed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtMultiplier = new javax.swing.JTextField();
        jtxtD = new javax.swing.JTextField();
        panelYellow3 = new ui.PanelYellow();
        jlblDekripsiTransformAffine = new javax.swing.JLabel();
        jlblDekripsiAffineHillCipher = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Decryption Form");

        panelYellow1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlblGambarUji1.setForeground(new java.awt.Color(255, 255, 255));
        jlblGambarUji1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblGambarUji1.setText("Browse Affine Transform Cipher");
        jlblGambarUji1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jlblGambarUji1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblGambarUji1MouseClicked(evt);
            }
        });

        jlblGambarUji2.setForeground(new java.awt.Color(255, 255, 255));
        jlblGambarUji2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblGambarUji2.setText("Browse Advance HC Cipher");
        jlblGambarUji2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jlblGambarUji2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblGambarUji2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelYellow1Layout = new javax.swing.GroupLayout(panelYellow1);
        panelYellow1.setLayout(panelYellow1Layout);
        panelYellow1Layout.setHorizontalGroup(
            panelYellow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelYellow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblGambarUji2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblGambarUji1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelYellow1Layout.setVerticalGroup(
            panelYellow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblGambarUji1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblGambarUji2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelYellow2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter Affine"));

        jtxtk2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtk2.setText("8");

        jLabel7.setText("K2");

        jtxtk1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtk1.setText("31");

        jLabel6.setText("K1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtk1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtk2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelYellow2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, 70));

        btnJalankanDekripsi.setText("Run Decryption");
        btnJalankanDekripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJalankanDekripsiActionPerformed(evt);
            }
        });
        panelYellow2.add(btnJalankanDekripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 250, 39));

        btnSimpanGambar.setText("Save Image");
        btnSimpanGambar.setEnabled(false);
        btnSimpanGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanGambarActionPerformed(evt);
            }
        });
        panelYellow2.add(btnSimpanGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 250, 39));

        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Exit");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelYellow2.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 250, 46));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("METHODS");
        panelYellow2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 37, 98, -1));

        buttonGroup1.add(jrbtnMetodeAT);
        jrbtnMetodeAT.setForeground(new java.awt.Color(255, 255, 255));
        jrbtnMetodeAT.setText("Affine Transform");
        panelYellow2.add(jrbtnMetodeAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        buttonGroup1.add(jrbtnMetodeATAHC);
        jrbtnMetodeATAHC.setForeground(new java.awt.Color(255, 255, 255));
        jrbtnMetodeATAHC.setText("Affine Transform +  Advanced Hill Cipher");
        panelYellow2.add(jrbtnMetodeATAHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 258, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter Hill Cipher"));

        jLabel3.setText("Seed");

        jtxtSeed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSeed.setText("5");

        jLabel4.setText("Mulltiplier");

        jLabel5.setText("d");

        jtxtMultiplier.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMultiplier.setText("7");

        jtxtD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtD.setText("3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtD)
                    .addComponent(jtxtMultiplier)
                    .addComponent(jtxtSeed, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtSeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtMultiplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelYellow2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 250, -1));

        jlblDekripsiTransformAffine.setForeground(new java.awt.Color(255, 255, 255));
        jlblDekripsiTransformAffine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDekripsiTransformAffine.setText("Affine Transform Decryption Result");
        jlblDekripsiTransformAffine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jlblDekripsiAffineHillCipher.setForeground(new java.awt.Color(255, 255, 255));
        jlblDekripsiAffineHillCipher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDekripsiAffineHillCipher.setText("Hasil Dekripsi Affine + Advanced Hill Cipher");
        jlblDekripsiAffineHillCipher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout panelYellow3Layout = new javax.swing.GroupLayout(panelYellow3);
        panelYellow3.setLayout(panelYellow3Layout);
        panelYellow3Layout.setHorizontalGroup(
            panelYellow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelYellow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlblDekripsiAffineHillCipher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblDekripsiTransformAffine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelYellow3Layout.setVerticalGroup(
            panelYellow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlblDekripsiTransformAffine, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblDekripsiAffineHillCipher, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelYellow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelYellow2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelYellow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelYellow3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelYellow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelYellow2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_btnKeluarActionPerformed

private void btnJalankanDekripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJalankanDekripsiActionPerformed
// TODO add your handling code here:
    if (gbr1==null || gbr2==null)
    {
          JOptionPane.showMessageDialog(null, "Anda Belum Memilih Gambar!","Peringatan",JOptionPane.WARNING_MESSAGE);
    }else{
    if (jrbtnMetodeAT.isSelected()) 
    {
     int a = Integer.parseInt(jtxtk1.getText());
     int b = Integer.parseInt(jtxtk2.getText());
     
     Affine affine  = new Affine(a,b);
     affine.decrypt(gbr1.getPixelAsli());
 //   affine.decrypt(affine.getResult());
    gbr1.setPixeloutput(affine.getResult());
    ImageViewer imgv = new ImageViewer();
    imgv.setImage(gbr1);
    imgv.setViewer(jlblDekripsiTransformAffine);
    imgv.viewImageOutput();
    btnSimpanGambar.setEnabled(true);
    }else if (jrbtnMetodeATAHC.isSelected()){
    
            int a = Integer.parseInt(jtxtk1.getText());
     int b = Integer.parseInt(jtxtk2.getText());
        
    int seed = Integer.parseInt(jtxtSeed.getText());
    int k = Integer.parseInt(jtxtD.getText());
    int multiplier = Integer.parseInt(jtxtMultiplier.getText());  

     HillCipher hc = new HillCipher(seed,k, multiplier,gbr2.getWidth());   
     int pixels[][] =null;
     for(int r=0;r<16;r++) 
     {
       pixels = gbr2.getPixelOutput();
      
       for(int i=0;i<pixels.length;i++)
       {
              int vecplain[] = Matrix.getVecOfRow(pixels, i);
              Permutation.runIPermutate(vecplain); 
              int cipher[] = hc.decrypt(vecplain);             
              gbr2.setPixelOutput(i, cipher);
       }
     }
     
    ImageViewer imgv = new ImageViewer();
    
    Affine affine  = new Affine(a,b);
    affine.decrypt(gbr2.getPixelOutput());
    gbr2.setPixeloutput(affine.getResult());    
    imgv.setImage(gbr2);
    imgv.setViewer(jlblDekripsiAffineHillCipher);
    imgv.viewImageOutput();
    btnSimpanGambar.setEnabled(true);
    }else {
         JOptionPane.showMessageDialog(null, "Anda Belum Memilih Metode Dekripsi!","Peringatan",JOptionPane.WARNING_MESSAGE);
    }
    }
}//GEN-LAST:event_btnJalankanDekripsiActionPerformed
public void saveFirstPicOutput() 
{
       JFileChooser  fc = new JFileChooser();
        FileFilter filter1 = new ExtensionFileFilter("Picture Files", new String[] { "JPG","TIFF","PNG","BMP"});
       fc.setFileFilter(filter1);
       String filesimpan = "";
       int respon =  fc.showSaveDialog(null);
       if (respon == fc.APPROVE_OPTION)
       {
            int w = gbr1.getWidth();
            int h =  gbr1.getHeight();
            int pixwm[] = gbr1.toOneDimensionalPixelOutput();
            BufferedImage image = new BufferedImage(w , h , BufferedImage.TYPE_INT_RGB);     
            image.setRGB(0, 0, w , h ,pixwm, 0, w);
            BufferedImage bf =image;
            File outputfile = new File(fc.getSelectedFile().getAbsolutePath());
            try{
              String fileapp = fc.getSelectedFile().getAbsolutePath();
             if (fileapp.contains("jpg")) 
             {
                  ImageIO.write(bf, "jpg", outputfile);
             }else  if (fileapp.contains("png")) 
             {
                  ImageIO.write(bf, "png", outputfile);
             }else if (fileapp.contains("tiff")) 
             {
                  ImageIO.write(bf, "tiff", outputfile);
             }else if (fileapp.contains("bmp")) 
             {
                  ImageIO.write(bf, "bmp", outputfile);
             }
             JOptionPane.showMessageDialog(null, "Citra Hasil Enkripsi Berhasil disimpan!");
            }catch(IOException e){
                 
            }

       }
}

public void saveSecondPicOutput() {
     JFileChooser  fc = new JFileChooser();
       FileFilter filter1 = new ExtensionFileFilter("Picture Files", new String[] { "JPG","TIFF","PNG","BMP"});
       fc.setFileFilter(filter1);
       String filesimpan = "";
       int respon =  fc.showSaveDialog(null);
       if (respon == fc.APPROVE_OPTION)
       {
            int w = gbr2.getWidth();
            int h =  gbr2.getHeight();
            int pixwm[] = gbr2.toOneDimensionalPixelOutput();
            BufferedImage image = new BufferedImage(w , h , BufferedImage.TYPE_INT_RGB);     
            image.setRGB(0, 0, w , h ,pixwm, 0, w);
            BufferedImage bf =image;
            File outputfile = new File(fc.getSelectedFile().getAbsolutePath());
            try{
              String fileapp = fc.getSelectedFile().getAbsolutePath();
             if (fileapp.contains("jpg")) 
             {
                  ImageIO.write(bf, "jpg", outputfile);
             }else  if (fileapp.contains("png")) 
             {
                  ImageIO.write(bf, "png", outputfile);
             }else if (fileapp.contains("tiff")) 
             {
                  ImageIO.write(bf, "tiff", outputfile);
             }else if (fileapp.contains("bmp")) 
             {
                  ImageIO.write(bf, "bmp", outputfile);
             }
             JOptionPane.showMessageDialog(null, "Citra Hasil Enkripsi Berhasil disimpan!");
            }catch(IOException e){
                 
            }

       }
}
private void btnSimpanGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanGambarActionPerformed
// TODO add your handling code here:
    if (jrbtnMetodeAT.isSelected()) 
    {
      saveFirstPicOutput();
    }else{
      saveSecondPicOutput();
    }
}//GEN-LAST:event_btnSimpanGambarActionPerformed

private void jlblGambarUji1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblGambarUji1MouseClicked
// TODO add your handling code here:
    JFileChooser flchooser = new JFileChooser();
    FileFilter filter1 = new ExtensionFileFilter("Picture Files", new String[] { "JPG","TIFF","PNG","BMP"});
    flchooser.setFileFilter(filter1);
    int tanggapan = flchooser.showOpenDialog(this);   
    if(tanggapan==JFileChooser.APPROVE_OPTION)
    {
        BufferedImage img=null;
        try
        {
         img = ImageIO.read(flchooser.getSelectedFile());
        }catch(IOException ex)
        {
            
        }
       
        ImageIcon imgicon = new ImageIcon(img); 
        ImageReader imgLoader = new ImageReader();
        imgLoader.readPixelsFrom(imgicon);
        gbr1 = imgLoader.getImage();       
        ImageViewer imgv = new ImageViewer();
        imgv.setImage(gbr1);
        imgv.setViewer(jlblGambarUji1);
        imgv.viewImageDefault();
           
    }
}//GEN-LAST:event_jlblGambarUji1MouseClicked

private void jlblGambarUji2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblGambarUji2MouseClicked
// TODO add your handling code here:
     JFileChooser flchooser = new JFileChooser();
     FileFilter filter1 = new ExtensionFileFilter("Picture Files", new String[] { "JPG","TIFF","PNG","BMP"});
    flchooser.setFileFilter(filter1);
    int tanggapan = flchooser.showOpenDialog(this);   
    if(tanggapan==JFileChooser.APPROVE_OPTION)
    {
        BufferedImage img=null;
        try
        {
         img = ImageIO.read(flchooser.getSelectedFile());
        }catch(IOException ex)
        {
            
        }
       
        ImageIcon imgicon = new ImageIcon(img); 
        ImageReader imgLoader = new ImageReader();
        imgLoader.readPixelsFrom(imgicon);
        gbr2 = imgLoader.getImage();       
        ImageViewer imgv = new ImageViewer();
        imgv.setImage(gbr2);
        imgv.setViewer(jlblGambarUji2);
        imgv.viewImageDefault();
        
          
    }
}//GEN-LAST:event_jlblGambarUji2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDecryptImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDecryptImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDecryptImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDecryptImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormDecryptImage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.ButtonGlass btnJalankanDekripsi;
    private ui.ButtonGlass btnKeluar;
    private ui.ButtonGlass btnSimpanGambar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlblDekripsiAffineHillCipher;
    private javax.swing.JLabel jlblDekripsiTransformAffine;
    private javax.swing.JLabel jlblGambarUji1;
    private javax.swing.JLabel jlblGambarUji2;
    private javax.swing.JRadioButton jrbtnMetodeAT;
    private javax.swing.JRadioButton jrbtnMetodeATAHC;
    private javax.swing.JTextField jtxtD;
    private javax.swing.JTextField jtxtMultiplier;
    private javax.swing.JTextField jtxtSeed;
    private javax.swing.JTextField jtxtk1;
    private javax.swing.JTextField jtxtk2;
    private ui.PanelYellow panelYellow1;
    private ui.PanelYellow panelYellow2;
    private ui.PanelYellow panelYellow3;
    // End of variables declaration//GEN-END:variables
}
